curlStuff
std::string curlStuff::cbc
Referenced by clipUrl, dlgNewLink::dlgNewLink.
curlStuff::curlStuff()
curlStuff::~curlStuff()
std::string curlStuff::getZTitle(std::string url)
References curl_read.
Referenced by clipUrl.
std::string curlStuff::clipUrl()
References cbc, getURL, getZTitle.
Referenced by dlgNewLink::dlgNewLink.
std::string curlStuff::getURL()
Referenced by clipUrl.