.TH "bcsGui.cpp" 3 "cppMD01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bcsGui.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'bcsGui\&.h'\fP
.br
\fR#include <wx/wx\&.h>\fP
.br
\fR#include <wx/dirdlg\&.h>\fP
.br
\fR#include <wx/textdlg\&.h>\fP
.br
\fR#include <wx/msgdlg\&.h>\fP
.br
\fR#include <wx/string\&.h>\fP
.br
\fR#include <wx/window\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for cppMD01 from the source code\&.
