.TH "bcsGui" 3 "cppMD01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bcsGui
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBSelDir\fP (string initDir)"
.br
.ti -1c
.RI "string \fBGetText\fP (bool memo, string initVal, string prompt, string caption)"
.br
.ti -1c
.RI "int \fByornQues\fP (string caption, string prompt)"
.br
.ti -1c
.RI "string \fBopenFileDialog\fP (wxWindow *parent, const wxString &message, const wxString &defaultDir, const wxString &defaultFile, const wxString &wildcard, int flags)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cppMD01 from the source code\&.
