.TH "cppMD01Frame" 3 "cppMD01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cppMD01Frame
.SH SYNOPSIS
.br
.PP
.PP
Inherits wxFrame\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcppMD01Frame\fP (wxWindow *parent, wxWindowID id=\-1)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "mysqlpp::Connection \fBconn\fP"
.br
.ti -1c
.RI "wxGrid * \fBmasterGrid\fP"
.br
.ti -1c
.RI "wxGrid * \fBdetailGrid\fP"
.br
.ti -1c
.RI "std::string \fBcmd\fP"
.br
.ti -1c
.RI "std::string \fBmkVal\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cppMD01 from the source code\&.
