.TH "cppMD01Main.cpp" 3 "cppMD01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cppMD01Main.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'cppMD01Main\&.h'\fP
.br
\fR#include <wx/msgdlg\&.h>\fP
.br
\fR#include <wx/grid\&.h>\fP
.br
\fR#include <mysql++\&.h>\fP
.br
\fR#include <mysql\&.h>\fP
.br
\fR#include <wx/hyperlink\&.h>\fP
.br
\fR#include <wx/filedlg\&.h>\fP
.br
\fR#include <wx/log\&.h>\fP
.br
\fR#include <boost/filesystem\&.hpp>\fP
.br
\fR#include <boost/algorithm/string\&.hpp>\fP
.br
\fR#include 'dlgXqt2\&.h'\fP
.br
\fR#include 'dlgNewLink\&.h'\fP
.br
\fR#include 'zDB01\&.h'\fP
.br
\fR#include 'bcsGui\&.h'\fP
.br
\fR#include 'dlgSelDB\&.h'\fP
.br
\fR#include 'dlgNewCat\&.h'\fP
.br
\fR#include 'wx/clipbrd\&.h'\fP
.br
\fR#include 'dlgSelCat\&.h'\fP
.br
\fR#include <wx/wx\&.h>\fP
.br
\fR#include <wx/intl\&.h>\fP
.br
\fR#include <wx/string\&.h>\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBwxbuildinfoformat\fP { \fBshort_f\fP, \fBlong_f\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "wxString \fBwxbuildinfo\fP (\fBwxbuildinfoformat\fP format)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBzDB01\fP \fBzrdb\fP"
.br
.ti -1c
.RI "\fBbcsGui\fP \fBgui01\fP"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBwxbuildinfoformat\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIshort_f \fP\fP
.TP
\fB\fIlong_f \fP\fP
.PP
Definition at line \fB37\fP of file \fBcppMD01Main\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "wxString wxbuildinfo (\fBwxbuildinfoformat\fP format)"

.PP
Definition at line \fB45\fP of file \fBcppMD01Main\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBbcsGui\fP gui01"

.PP
Definition at line \fB43\fP of file \fBcppMD01Main\&.cpp\fP\&.
.SS "\fBzDB01\fP zrdb"

.PP
Definition at line \fB42\fP of file \fBcppMD01Main\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for cppMD01 from the source code\&.
