.TH "cppMD01Frame" 3 "cppMD01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cppMD01Frame
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <cppMD01Main\&.h>\fP
.PP
Inherits wxFrame\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcppMD01Frame\fP (wxWindow *parent, wxWindowID id=\-1)"
.br
.ti -1c
.RI "virtual \fB~cppMD01Frame\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "mysqlpp::Connection \fBconn\fP"
.br
.ti -1c
.RI "wxGrid * \fBmasterGrid\fP"
.br
.ti -1c
.RI "wxGrid * \fBdetailGrid\fP"
.br
.ti -1c
.RI "std::string \fBcmd\fP"
.br
.ti -1c
.RI "std::string \fBmkVal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB26\fP of file \fBcppMD01Main\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cppMD01Frame::cppMD01Frame (wxWindow * parent, wxWindowID id = \fR\-1\fP)"

.PP
Definition at line \fB93\fP of file \fBcppMD01Main\&.cpp\fP\&.
.SS "cppMD01Frame::~cppMD01Frame ()\fR [virtual]\fP"

.PP
Definition at line \fB230\fP of file \fBcppMD01Main\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string cppMD01Frame::cmd"

.PP
Definition at line \fB35\fP of file \fBcppMD01Main\&.h\fP\&.
.SS "mysqlpp::Connection cppMD01Frame::conn"

.PP
Definition at line \fB32\fP of file \fBcppMD01Main\&.h\fP\&.
.SS "wxGrid* cppMD01Frame::detailGrid"

.PP
Definition at line \fB34\fP of file \fBcppMD01Main\&.h\fP\&.
.SS "wxGrid* cppMD01Frame::masterGrid"

.PP
Definition at line \fB33\fP of file \fBcppMD01Main\&.h\fP\&.
.SS "std::string cppMD01Frame::mkVal"

.PP
Definition at line \fB36\fP of file \fBcppMD01Main\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cppMD01 from the source code\&.
