.TH "cppMD01App" 3 "cppMD01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cppMD01App
.SH SYNOPSIS
.br
.PP
.PP
Inherits wxApp\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBOnInit\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cppMD01 from the source code\&.
