.TH "curlStuff" 3 "cppMD01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
curlStuff
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <curlStuff\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcurlStuff\fP ()"
.br
.ti -1c
.RI "virtual \fB~curlStuff\fP ()"
.br
.ti -1c
.RI "std::string \fBgetZTitle\fP (std::string url)"
.br
.ti -1c
.RI "std::string \fBclipUrl\fP ()"
.br
.ti -1c
.RI "std::string \fBgetURL\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBcbc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBcurlStuff\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "curlStuff::curlStuff ()"

.PP
Definition at line \fB18\fP of file \fBcurlStuff\&.cpp\fP\&.
.SS "curlStuff::~curlStuff ()\fR [virtual]\fP"

.PP
Definition at line \fB23\fP of file \fBcurlStuff\&.cpp\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string curlStuff::clipUrl ()"

.PP
Definition at line \fB189\fP of file \fBcurlStuff\&.cpp\fP\&.
.SS "std::string curlStuff::getURL ()"

.PP
Definition at line \fB169\fP of file \fBcurlStuff\&.cpp\fP\&.
.SS "std::string curlStuff::getZTitle (std::string url)"

.PP
Definition at line \fB76\fP of file \fBcurlStuff\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string curlStuff::cbc"

.PP
Definition at line \fB14\fP of file \fBcurlStuff\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cppMD01 from the source code\&.
