.TH "curlStuff" 3 "cppMD01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
curlStuff
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBgetZTitle\fP (std::string url)"
.br
.ti -1c
.RI "std::string \fBclipUrl\fP ()"
.br
.ti -1c
.RI "std::string \fBgetURL\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBcbc\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cppMD01 from the source code\&.
