.TH "curlStuff.cpp" 3 "cppMD01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
curlStuff.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'curlStuff\&.h'\fP
.br
\fR#include <string>\fP
.br
\fR#include <curl/curl\&.h>\fP
.br
\fR#include <fstream>\fP
.br
\fR#include <ios>\fP
.br
\fR#include <strstream>\fP
.br
\fR#include <sstream>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <curl/easy\&.h>\fP
.br
\fR#include <boost/algorithm/string\&.hpp>\fP
.br
\fR#include <wx/clipbrd\&.h>\fP
.br
\fR#include <wx/msgdlg\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "CURLcode \fBcurl_read\fP (const std::string &url, std::ostream &os, long timeout=30)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "CURLcode curl_read (const std::string & url, std::ostream & os, long timeout = \fR30\fP)"

.PP
Definition at line \fB41\fP of file \fBcurlStuff\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for cppMD01 from the source code\&.
