.TH "dlgDe01" 3 "cppMD01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dlgDe01
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <dlgDe01\&.h>\fP
.PP
Inherits wxDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdlgDe01\fP (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)"
.br
.ti -1c
.RI "virtual \fB~dlgDe01\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "wxStaticText * \fBStaticText1\fP"
.br
.ti -1c
.RI "wxStaticText * \fBStaticText2\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBTextCtrl1\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBTextCtrl2\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static const long \fBID_STATICTEXT1\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_TEXTCTRL1\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_STATICTEXT2\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_TEXTCTRL2\fP = wxNewId()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBdlgDe01\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "dlgDe01::dlgDe01 (wxWindow * parent, wxWindowID id = \fRwxID_ANY\fP, const wxPoint & pos = \fRwxDefaultPosition\fP, const wxSize & size = \fRwxDefaultSize\fP)"

.PP
Definition at line \fB20\fP of file \fBdlgDe01\&.cpp\fP\&.
.SS "dlgDe01::~dlgDe01 ()\fR [virtual]\fP"

.PP
Definition at line \fB52\fP of file \fBdlgDe01\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const long dlgDe01::ID_STATICTEXT1 = wxNewId()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB28\fP of file \fBdlgDe01\&.h\fP\&.
.SS "const long dlgDe01::ID_STATICTEXT2 = wxNewId()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB30\fP of file \fBdlgDe01\&.h\fP\&.
.SS "const long dlgDe01::ID_TEXTCTRL1 = wxNewId()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB29\fP of file \fBdlgDe01\&.h\fP\&.
.SS "const long dlgDe01::ID_TEXTCTRL2 = wxNewId()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB31\fP of file \fBdlgDe01\&.h\fP\&.
.SS "wxStaticText* dlgDe01::StaticText1"

.PP
Definition at line \fB19\fP of file \fBdlgDe01\&.h\fP\&.
.SS "wxStaticText* dlgDe01::StaticText2"

.PP
Definition at line \fB20\fP of file \fBdlgDe01\&.h\fP\&.
.SS "wxTextCtrl* dlgDe01::TextCtrl1"

.PP
Definition at line \fB21\fP of file \fBdlgDe01\&.h\fP\&.
.SS "wxTextCtrl* dlgDe01::TextCtrl2"

.PP
Definition at line \fB22\fP of file \fBdlgDe01\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cppMD01 from the source code\&.
