.TH "dlgNewLink" 3 "cppMD01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dlgNewLink
.SH SYNOPSIS
.br
.PP
.PP
Inherits wxDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdlgNewLink\fP (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "wxButton * \fBbtnCancel\fP"
.br
.ti -1c
.RI "wxButton * \fBbtnInset\fP"
.br
.ti -1c
.RI "wxStaticText * \fBlblDet\fP"
.br
.ti -1c
.RI "wxStaticText * \fBlblLink\fP"
.br
.ti -1c
.RI "wxStaticText * \fBlblidlk1\fP"
.br
.ti -1c
.RI "wxStaticText * \fBlnlLinkName\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBedtDetDes\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBedtLink\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBedtLinkName\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBedtPrim\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static const long \fBID_STATICTEXT1\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_TEXTCTRL1\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_STATICTEXT2\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_TEXTCTRL2\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_STATICTEXT3\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_TEXTCTRL3\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_STATICTEXT4\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_TEXTCTRL4\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_BUTTON1\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_BUTTON2\fP = wxNewId()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "dlgNewLink::dlgNewLink (wxWindow * parent, wxWindowID id = \fRwxID_ANY\fP, const wxPoint & pos = \fRwxDefaultPosition\fP, const wxSize & size = \fRwxDefaultSize\fP)"
zrdb\&.initField(mkVal,dlg\&.edtPrim);

.SH "Author"
.PP 
Generated automatically by Doxygen for cppMD01 from the source code\&.
