.TH "dlgNb01" 3 "cppMD01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dlgNb01
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <dlgNb01\&.h>\fP
.PP
Inherits wxDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdlgNb01\fP (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)"
.br
.ti -1c
.RI "virtual \fB~dlgNb01\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcurCat\fP"
.br
.ti -1c
.RI "wxListBox * \fBlbxCats\fP"
.br
.ti -1c
.RI "wxListBox * \fBlbxLinks\fP"
.br
.ti -1c
.RI "wxNotebook * \fBnbk01\fP"
.br
.ti -1c
.RI "wxPanel * \fBPanel1\fP"
.br
.ti -1c
.RI "wxPanel * \fBPanel2\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static const long \fBID_LISTBOX1\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_PANEL1\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_LISTBOX2\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_PANEL2\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_NOTEBOOK1\fP = wxNewId()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBdlgNb01\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "dlgNb01::dlgNb01 (wxWindow * parent, wxWindowID id = \fRwxID_ANY\fP, const wxPoint & pos = \fRwxDefaultPosition\fP, const wxSize & size = \fRwxDefaultSize\fP)"

.PP
Definition at line \fB24\fP of file \fBdlgNb01\&.cpp\fP\&.
.SS "dlgNb01::~dlgNb01 ()\fR [virtual]\fP"

.PP
Definition at line \fB69\fP of file \fBdlgNb01\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int dlgNb01::curCat"

.PP
Definition at line \fB18\fP of file \fBdlgNb01\&.h\fP\&.
.SS "const long dlgNb01::ID_LISTBOX1 = wxNewId()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB31\fP of file \fBdlgNb01\&.h\fP\&.
.SS "const long dlgNb01::ID_LISTBOX2 = wxNewId()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB33\fP of file \fBdlgNb01\&.h\fP\&.
.SS "const long dlgNb01::ID_NOTEBOOK1 = wxNewId()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB35\fP of file \fBdlgNb01\&.h\fP\&.
.SS "const long dlgNb01::ID_PANEL1 = wxNewId()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB32\fP of file \fBdlgNb01\&.h\fP\&.
.SS "const long dlgNb01::ID_PANEL2 = wxNewId()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB34\fP of file \fBdlgNb01\&.h\fP\&.
.SS "wxListBox* dlgNb01::lbxCats"

.PP
Definition at line \fB21\fP of file \fBdlgNb01\&.h\fP\&.
.SS "wxListBox* dlgNb01::lbxLinks"

.PP
Definition at line \fB22\fP of file \fBdlgNb01\&.h\fP\&.
.SS "wxNotebook* dlgNb01::nbk01"

.PP
Definition at line \fB23\fP of file \fBdlgNb01\&.h\fP\&.
.SS "wxPanel* dlgNb01::Panel1"

.PP
Definition at line \fB24\fP of file \fBdlgNb01\&.h\fP\&.
.SS "wxPanel* dlgNb01::Panel2"

.PP
Definition at line \fB25\fP of file \fBdlgNb01\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cppMD01 from the source code\&.
