.TH "dlgNewLink.h" 3 "cppMD01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dlgNewLink.h
.SH SYNOPSIS
.br
.PP
\fR#include <wx/button\&.h>\fP
.br
\fR#include <wx/dialog\&.h>\fP
.br
\fR#include <wx/sizer\&.h>\fP
.br
\fR#include <wx/stattext\&.h>\fP
.br
\fR#include <wx/textctrl\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdlgNewLink\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cppMD01 from the source code\&.
