.TH "dlgNb01.cpp" 3 "cppMD01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dlgNb01.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'dlgNb01\&.h'\fP
.br
\fR#include 'zDB01\&.h'\fP
.br
\fR#include <wx/intl\&.h>\fP
.br
\fR#include <wx/string\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBzDB01\fP \fBrdb\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBzDB01\fP rdb"

.PP
Definition at line \fB4\fP of file \fBdlgNb01\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for cppMD01 from the source code\&.
