.TH "dlgNb01.h" 3 "cppMD01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dlgNb01.h
.SH SYNOPSIS
.br
.PP
\fR#include <wx/dialog\&.h>\fP
.br
\fR#include <wx/listbox\&.h>\fP
.br
\fR#include <wx/notebook\&.h>\fP
.br
\fR#include <wx/panel\&.h>\fP
.br
\fR#include <wx/sizer\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdlgNb01\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cppMD01 from the source code\&.
