.TH "dlgNewCat" 3 "cppMD01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dlgNewCat
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <dlgNewCat\&.h>\fP
.PP
Inherits wxDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdlgNewCat\fP (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)"
.br
.ti -1c
.RI "virtual \fB~dlgNewCat\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "wxButton * \fBbtnCancel\fP"
.br
.ti -1c
.RI "wxButton * \fBbtnInsert\fP"
.br
.ti -1c
.RI "wxStaticText * \fBlblCat\fP"
.br
.ti -1c
.RI "wxStaticText * \fBlblMemo\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBedtCat\fP"
.br
.ti -1c
.RI "wxTextCtrl * \fBedtMemo\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static const long \fBID_STATICTEXT1\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_TEXTCTRL1\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_STATICTEXT2\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_TEXTCTRL2\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_BUTTON1\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_BUTTON2\fP = wxNewId()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBdlgNewCat\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "dlgNewCat::dlgNewCat (wxWindow * parent, wxWindowID id = \fRwxID_ANY\fP, const wxPoint & pos = \fRwxDefaultPosition\fP, const wxSize & size = \fRwxDefaultSize\fP)"

.PP
Definition at line \fB25\fP of file \fBdlgNewCat\&.cpp\fP\&.
.SS "dlgNewCat::~dlgNewCat ()\fR [virtual]\fP"

.PP
Definition at line \fB64\fP of file \fBdlgNewCat\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "wxButton* dlgNewCat::btnCancel"

.PP
Definition at line \fB20\fP of file \fBdlgNewCat\&.h\fP\&.
.SS "wxButton* dlgNewCat::btnInsert"

.PP
Definition at line \fB21\fP of file \fBdlgNewCat\&.h\fP\&.
.SS "wxTextCtrl* dlgNewCat::edtCat"

.PP
Definition at line \fB24\fP of file \fBdlgNewCat\&.h\fP\&.
.SS "wxTextCtrl* dlgNewCat::edtMemo"

.PP
Definition at line \fB25\fP of file \fBdlgNewCat\&.h\fP\&.
.SS "const long dlgNewCat::ID_BUTTON1 = wxNewId()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB35\fP of file \fBdlgNewCat\&.h\fP\&.
.SS "const long dlgNewCat::ID_BUTTON2 = wxNewId()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB36\fP of file \fBdlgNewCat\&.h\fP\&.
.SS "const long dlgNewCat::ID_STATICTEXT1 = wxNewId()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB31\fP of file \fBdlgNewCat\&.h\fP\&.
.SS "const long dlgNewCat::ID_STATICTEXT2 = wxNewId()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB33\fP of file \fBdlgNewCat\&.h\fP\&.
.SS "const long dlgNewCat::ID_TEXTCTRL1 = wxNewId()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB32\fP of file \fBdlgNewCat\&.h\fP\&.
.SS "const long dlgNewCat::ID_TEXTCTRL2 = wxNewId()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB34\fP of file \fBdlgNewCat\&.h\fP\&.
.SS "wxStaticText* dlgNewCat::lblCat"

.PP
Definition at line \fB22\fP of file \fBdlgNewCat\&.h\fP\&.
.SS "wxStaticText* dlgNewCat::lblMemo"

.PP
Definition at line \fB23\fP of file \fBdlgNewCat\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cppMD01 from the source code\&.
