.TH "dlgSelDB" 3 "cppMD01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dlgSelDB
.SH SYNOPSIS
.br
.PP
.PP
Inherits wxDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdlgSelDB\fP (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBbuf\fP"
.br
.ti -1c
.RI "wxListBox * \fBlbxDbNames\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static const long \fBID_LISTBOX1\fP = wxNewId()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cppMD01 from the source code\&.
