.TH "dlgXqt2.h" 3 "cppMD01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dlgXqt2.h
.SH SYNOPSIS
.br
.PP
\fR#include <wx/button\&.h>\fP
.br
\fR#include <wx/dialog\&.h>\fP
.br
\fR#include <wx/radiobox\&.h>\fP
.br
\fR#include <wx/sizer\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdlgXqt2\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for cppMD01 from the source code\&.
