.TH "dlgXqt2" 3 "cppMD01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dlgXqt2
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <dlgXqt2\&.h>\fP
.PP
Inherits wxDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdlgXqt2\fP (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)"
.br
.ti -1c
.RI "virtual \fB~dlgXqt2\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBisel\fP"
.br
.ti -1c
.RI "wxButton * \fBbutCancel\fP"
.br
.ti -1c
.RI "wxRadioBox * \fBrbtRadBut\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static const long \fBID_RADIOBOX1\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_BUTTON1\fP = wxNewId()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBdlgXqt2\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "dlgXqt2::dlgXqt2 (wxWindow * parent, wxWindowID id = \fRwxID_ANY\fP, const wxPoint & pos = \fRwxDefaultPosition\fP, const wxSize & size = \fRwxDefaultSize\fP)"

.PP
Definition at line \fB18\fP of file \fBdlgXqt2\&.cpp\fP\&.
.SS "dlgXqt2::~dlgXqt2 ()\fR [virtual]\fP"

.PP
Definition at line \fB53\fP of file \fBdlgXqt2\&.cpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "wxButton* dlgXqt2::butCancel"

.PP
Definition at line \fB21\fP of file \fBdlgXqt2\&.h\fP\&.
.SS "const long dlgXqt2::ID_BUTTON1 = wxNewId()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB29\fP of file \fBdlgXqt2\&.h\fP\&.
.SS "const long dlgXqt2::ID_RADIOBOX1 = wxNewId()\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB28\fP of file \fBdlgXqt2\&.h\fP\&.
.SS "int dlgXqt2::isel"

.PP
Definition at line \fB17\fP of file \fBdlgXqt2\&.h\fP\&.
.SS "wxRadioBox* dlgXqt2::rbtRadBut"

.PP
Definition at line \fB22\fP of file \fBdlgXqt2\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for cppMD01 from the source code\&.
