.TH "dlgXqt2" 3 "cppMD01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dlgXqt2
.SH SYNOPSIS
.br
.PP
.PP
Inherits wxDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdlgXqt2\fP (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBisel\fP"
.br
.ti -1c
.RI "wxButton * \fBbutCancel\fP"
.br
.ti -1c
.RI "wxRadioBox * \fBrbtRadBut\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static const long \fBID_RADIOBOX1\fP = wxNewId()"
.br
.ti -1c
.RI "static const long \fBID_BUTTON1\fP = wxNewId()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cppMD01 from the source code\&.
