var files_dup =
[
    [ "bcsGui.cpp", "bcs_gui_8cpp.html", null ],
    [ "bcsGui.h", "bcs_gui_8h.html", "bcs_gui_8h" ],
    [ "cppMD01App.cpp", "cpp_m_d01_app_8cpp.html", "cpp_m_d01_app_8cpp" ],
    [ "cppMD01App.h", "cpp_m_d01_app_8h.html", "cpp_m_d01_app_8h" ],
    [ "cppMD01Main.cpp", "cpp_m_d01_main_8cpp.html", "cpp_m_d01_main_8cpp" ],
    [ "cppMD01Main.h", "cpp_m_d01_main_8h.html", "cpp_m_d01_main_8h" ],
    [ "curlStuff.cpp", "curl_stuff_8cpp.html", "curl_stuff_8cpp" ],
    [ "curlStuff.h", "curl_stuff_8h.html", "curl_stuff_8h" ],
    [ "dlgDe01.cpp", "dlg_de01_8cpp.html", null ],
    [ "dlgDe01.h", "dlg_de01_8h.html", "dlg_de01_8h" ],
    [ "dlgNb01.cpp", "dlg_nb01_8cpp.html", "dlg_nb01_8cpp" ],
    [ "dlgNb01.h", "dlg_nb01_8h.html", "dlg_nb01_8h" ],
    [ "dlgNewCat.cpp", "dlg_new_cat_8cpp.html", "dlg_new_cat_8cpp" ],
    [ "dlgNewCat.h", "dlg_new_cat_8h.html", "dlg_new_cat_8h" ],
    [ "dlgNewLink.cpp", "dlg_new_link_8cpp.html", "dlg_new_link_8cpp" ],
    [ "dlgNewLink.h", "dlg_new_link_8h.html", "dlg_new_link_8h" ],
    [ "dlgSelDB.cpp", "dlg_sel_d_b_8cpp.html", null ],
    [ "dlgSelDB.h", "dlg_sel_d_b_8h.html", "dlg_sel_d_b_8h" ],
    [ "dlgXqt2.cpp", "dlg_xqt2_8cpp.html", null ],
    [ "dlgXqt2.h", "dlg_xqt2_8h.html", "dlg_xqt2_8h" ],
    [ "zDB01.cpp", "z_d_b01_8cpp.html", null ],
    [ "zDB01.h", "z_d_b01_8h.html", "z_d_b01_8h" ]
];